# general settings
name: train_MDRN_X2_depth_exp-0 #train_MDRN_X2_deblur #train_MDRN_X2_denoise #train_MDRN_X2
model_type: SRModel
scale: 2
num_gpu: 0 #auto  # set num_gpu: 0 for cpu mode
manual_seed: 1234

# dataset and data loader settings
datasets:
  train:
    name: HRWSI
    type: TripleImageDataset
    dataroot_gt: datasets/HRWSI/HRWSI_500_train_HR_images_sub
    dataroot_lq: datasets/HRWSI/HRWSI_500_train_HR_images_X2_sub
    dataroot_depth: datasets/HRWSI/HRWSI_500_train_HR_depths_X2_sub
#    meta_info_file: basicsr/data/meta_info/meta_info_DIV2K800sub_GT.txt
    # (for lmdb)
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb
#    pin_memory: true
    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4 #8  # If Broken Pipe (set small, as 4)
    batch_size_per_gpu: 8 #64 #32 #64
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: HRWSI
    type: TripleImageDataset
    dataroot_gt: datasets/testsets/HRWSI/HR_mod2
    dataroot_lq: datasets/testsets/HRWSI/X2
    dataroot_depth: datasets/testsets/HRWSI/X2_depths
    io_backend:
      type: disk

# network structures
network_g:
  type: MDRN
  upscale: 2
  num_in_ch: 3

# path
path:
  pretrain_network_g: /home/arazin/main/work/huawei_cv/ISR_Basic_With_Depth/pretrain_models/mdrn/mdrn_x2.pth #~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0 #0.999 ????
  optim_g:
    type: Adam
    lr: !!float 2e-3
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [5000, 100000, 500000, 800000, 900000, 950000]
    gamma: 0.5

  total_iter: 10000 #1000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1

# validation settings
val:
  val_freq: !!float 5e2
  save_img: true #false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: basicsr_depth
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
